CREATE TABLE IF NOT EXISTS tasks (
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       task_name VARCHAR(255) NOT NULL,
                       task_description TEXT,
                       task_status VARCHAR(50) NOT NULL,
                       start_date TIMESTAMP,
                       end_date TIMESTAMP,
                       deadline TIMESTAMP,
                       project_id INT,
                       active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS task_users (
                            task_id INT NOT NULL,
                            user_id INT NOT NULL,
                            FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
                            PRIMARY KEY (task_id, user_id)
);